apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server
  namespace: app
spec:
  ports:
  - name: 9090-9090
    nodePort: 30000
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: server
  type: NodePort
status:
  loadBalancer: {}
